"""Map data.csv headers to snake_case column names."""

COLUMN_MAP: dict[str, str] = {
    "Song": "song",
    "Artist": "artist",
    "Date": "date",
    "Weeks at Number One": "weeks_at_number_one",
    "Non-Consecutive": "non_consecutive",
    "Rating 1": "rating_1",
    "Rating 2": "rating_2",
    "Rating 3": "rating_3",
    "Overall Rating": "overall_rating",
    "Divisiveness": "divisiveness",
    "Label": "label",
    "Parent Label": "parent_label",
    "CDR Genre": "cdr_genre",
    "CDR Style": "cdr_style",
    "Discogs Genre": "discogs_genre",
    "Discogs Style": "discogs_style",
    "Artist Structure": "artist_structure",
    "Featured Artists": "featured_artists",
    "Multiple Lead Vocalists": "multiple_lead_vocalists",
    "Group Named After Non-Lead Singer": "group_named_after_non_lead",
    "Talent Contestant": "talent_contestant",
    "Posthumous": "posthumous",
    "Artist Place of Origin": "artist_place_of_origin",
    "Front Person Age": "front_person_age",
    "Artist Male": "artist_male",
    "Artist White": "artist_white",
    "Artist Black": "artist_black",
    "Songwriters": "songwriters",
    "Songwriters w/o Interpolation & Sample Credits": "songwriters_wo_interpolation_sample",
    "Songwriter Male": "songwriter_male",
    "Songwriter White": "songwriter_white",
    "Artist is a Songwriter": "artist_is_songwriter",
    "Artist is Only Songwriter": "artist_is_only_songwriter",
    "Producers": "producers",
    "Producer Male": "producer_male",
    "Producer White": "producer_white",
    "Artist is a Producer": "artist_is_producer",
    "Artist is Only Producer": "artist_is_only_producer",
    "Songwriter is a Producer": "songwriter_is_producer",
    "Time Signature": "time_signature",
    "Keys": "keys",
    "Simplified Key": "simplified_key",
    "BPM": "bpm",
    "Energy": "energy",
    "Danceability": "danceability",
    "Happiness": "happiness",
    "Loudness (dB)": "loudness_db",
    "Acousticness": "acousticness",
    "Vocally Based": "vocally_based",
    "Bass Based": "bass_based",
    "Guitar Based": "guitar_based",
    "Piano/Keyboard Based": "piano_based",
    "Orchestral Strings": "orchestral_strings",
    "Horns/Winds": "horns_winds",
    "Accordion": "accordion",
    "Banjo": "banjo",
    "Bongos": "bongos",
    "Clarinet": "clarinet",
    "Cowbell": "cowbell",
    "Falsetto Vocal": "falsetto_vocal",
    "Flute/Piccolo": "flute_piccolo",
    "Handclaps/Snaps": "handclaps_snaps",
    "Harmonica": "harmonica",
    "Human Whistling": "human_whistling",
    "Kazoo": "kazoo",
    "Mandolin": "mandolin",
    "Pedal/Lap Steel": "pedal_lap_steel",
    "Ocarina": "ocarina",
    "Saxophone": "saxophone",
    "Sitar": "sitar",
    "Trumpet": "trumpet",
    "Ukulele": "ukulele",
    "Violin": "violin",
    "Sound Effects": "sound_effects",
    "Song Structure": "song_structure",
    "Rap Verse in a Non-Rap Song": "rap_verse_non_rap",
    "Length (Sec)": "length_sec",
    "Instrumental": "instrumental",
    "Instrumental Length(Sec)": "instrumental_length_sec",
    "Intro Length (Sec)": "intro_length_sec",
    "Vocal Introduction": "vocal_introduction",
    "Free Time Vocal Introduction": "free_time_vocal_introduction",
    "Fade out": "fade_out",
    "Live": "live",
    "Cover": "cover",
    "Sample": "sample",
    "Interpolation": "interpolation",
    "Inspired by a Different Song": "inspired_by_different_song",
    "Lyrics": "lyrics",
    "Lyrical Topic": "lyrical_topic",
    "Lyrical Narrative": "lyrical_narrative",
    "Spoken Word": "spoken_word",
    "Explicit": "explicit",
    "Foreign Language": "foreign_language",
    "Written for a Play": "written_for_play",
    "Featured in a Then Contemporary Play": "featured_in_play",
    "Written for a Film": "written_for_film",
    "Featured in a Then Contemporary Film": "featured_in_film",
    "Written for a T.V. Show": "written_for_tv",
    "Featured in a then Contemporary T.V. Show": "featured_in_tv",
    "Associated with Dance": "associated_with_dance",
    "Topped the Charts by Multiple Artist": "topped_multiple_artists",
    "Double A Side": "double_a_side",
    "Eurovision Entry": "eurovision_entry",
    "U.S. Artwork": "us_artwork",
}
